version: '3'

services:  
  nginx: #服务名称
    image: nginx:latest
    ports:
    - 80:80
    volumes: # :Todo
    - /home/xmo/Documents/Code/Project/bxmo-blog/frontend/dist:/usr/share/nginx/html
    - /home/xmo/Documents/Code/Project/bxmo-blog/default.conf:/etc/nginx/conf.d/default.conf
    privileged: true